### ISSUE TITLE
importing error

### ISSUE THREAD

**Issue by villain** [MITRECND/WhoDat#11]
after the recent round of updates to the elasticsearch_import; im getting an error:

Errors making bulk api request!!
Bulk Requests saved to disk (/tmp/pydat-bulk-<identifier>-<random>.txt) and should be submitted manually!!
It is possible you are running too many bulk workers or the bulk size is too big!
ElasticSearch Bulk Syntax (using curl):
        curl -s -XPOST <es_server:port>/_bulk --data-binary @<bulk file name>
Bulk API error -- forcing program shutdown
Cleaning Up ... Please Wait ...
Warning!! Forcefully killing this might leave Elasticsearch in an inconsistent state!
        Shutting down input reader threads ...
        Stopping workers ...
        Waiting for ElasticSearch bulk uploads to finish ...
        Finalizing metadata
        Finalizing settings
... Done
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe

when i try to import manually with the curl command above:

# curl -s -XPOST http://127.0.0.1:9200/_bulk --data-binary @/tmp/pydat-bulk-3-5b37e8e6-0b14-11e6-a9cd-005056a1f827.txt 
{"took":270,"errors":true,"items":[{"create":{"_index":"whois-3","_type":"com","_id":"emctools","status":500,"error":"IllegalArgumentException[Document contains at least one immense term in field=\"details.registrant_email\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[97, 114, 109, 105, 110, 46, 108, 101, 110, 107, 64, 102, 114, 101, 101, 110, 101, 116, 46, 100, 101, 32, 116, 101, 99, 104, 95, 32, 97, 114]...', original message: bytes can be at most 32766 in length; got 39327]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 39327]; "}}]}

**Comment by Mraoul** [comment]
It's probably because I actually got around to adding error checking on the bulk responses, before I was firing and forgetting --  but this looks like one of the fields in the file is huge and/or malformed. Could you take a look at the bulk file and see what the registrant_email field looks like for the domain emctools.com?

**Comment by villain** [comment]
ah, looks like theyve messed up the data on the import. there's a bunch of fields that are all messed up for this domain

"registrant_email": "armin.lenk@freenet.de tech_ ar
min.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin
.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.le
nk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@
freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@fre
enet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freene
t.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.d
e tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de tech_ armin.lenk@freenet.de

etc..

**Comment by Mraoul** [comment]
Ugh, yeah, I've seen a lot of oddities in their dumps -- it'd be nice if they did some field sanitization before publishing a dump, or maybe I'm just being picky ...

Easiest way to fix this would be to fix the field, and then retry the bulk command. Keep in mind anything that succeeded before, will fail this time, so if you see an error message like "document already exists" (error code 409) or "document not found" (404) or something it probably succeeded. Alternatively you could modify that file to only run the ones that failed but I'm not sure I'd muck with that file unless you understand the bulk api format.
