### ISSUE TITLE
Unexpected behavior for files with no extension

### ISSUE THREAD

**Issue by ptcNOP** [MITRECND/WhoDat#17]
elasticsearch_populate always adds files without extension to queue to be processed ([here](https://github.com/MITRECND/WhoDat/blob/master/pydat/scripts/elasticsearch_populate.py#L357)) when using the `-d` flag. CSV exceptions are handled gracefully, but we could avoid adding files that don't match the extension by changing conditional to:

`if ext[1:] != self.options.extension:`

**Comment by Mraoul** [comment]
passing `-e '' ` should drop the extension check, thereby allowing any files. The extension check on that line definitely is a bug, I'll update
