### ISSUE TITLE
PassiveTotal usage

### ISSUE THREAD

**Issue by advancedeng** [MITRECND/WhoDat#6]
Hi all, 

As far as I can understand, for pDNS information only DNSDB can be used!
It would be a good idea to use PassiveTotal as well (or as an alternative compared to Farsight's commercial solution)? 
https://www.passivetotal.org/

Cheers,
Andreas

**Comment by wxsBSD** [comment]
This is something I think is a good idea. I've held off from doing it because I know passive total is undergoing a bit of a refactoring. I'm going to bug Brandon for an API key to the new one in the upcoming months.

**Comment by advancedeng** [comment]
The new PassiveTotal is up and running :) Any update on this?

**Comment by advancedeng** [comment]
FYI,
http://blog.passivetotal.org/api-updates-and-changes/

**Comment by wxsBSD** [comment]
I need to do some other work on a different project involving passivetotal, and then I will get to this. I don't have an ETA.

**Comment by wxsBSD** [comment]
I'm fairly certain I handled this so I'm going to close it. If that is incorrect please let me know!
